links:
  - storage_api: "http://10.98.12.18:8080/liqid/api/v2/status/storage?filter=true"
    gpu_api: "http://10.98.12.18:8080/liqid/api/v2/status/gpu?filter=true"
    host_api: "http://10.98.12.18:8080/liqid/api/v2/fabric/topology"
    mgmt_api: "http://10.98.12.18:8080/liqid/api/v2/fabric/topology"
